version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dotnet-crud-sql
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433" # changed external port to 1435 to avoid conflict with existing sql-1 container
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-crud-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    ports:
      - "8081:8080" # changed to 8081 in case 8080 is already used by another API
    depends_on:
      - sqlserver

volumes:
  sql_data:
